<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../Shared/OnVoyage.Recommendation.Engine/OnVoyage.Recommendation.Engine.csproj" />
    <ProjectReference Include="../../Services/Catalog/OnVoyage.Catalog.Contracts/OnVoyage.Catalog.Contracts.csproj" />
    <ProjectReference Include="../../Services/Discovery/OnVoyage.Discovery.Contracts/OnVoyage.Discovery.Contracts.csproj" />
    <ProjectReference Include="../../Services/Creators/OnVoyage.Creators.Contracts/OnVoyage.Creators.Contracts.csproj" />
    <ProjectReference Include="../../Services/Platform/OnVoyage.Platform.Contracts/OnVoyage.Platform.Contracts.csproj" />
    <ProjectReference Include="../../Services/Insights/OnVoyage.Insights.Contracts/OnVoyage.Insights.Contracts.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <ProjectReference Include="../../Shared/OnVoyage.Taxonomy/OnVoyage.Taxonomy.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="OnVoyage.App.Core.Tests" />
  </ItemGroup>
</Project>
