using System.Diagnostics;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Nodes;
using OnVoyage.TestInfrastructure;

namespace Factory.IntegrationTests;

/// <summary>The committed snapshot goes through the real states, audio and publication handlers, and the Catalog receives it through the real queues.</summary>
[Collection(PostgresTestGroup.Name)]
public sealed class SnapshotImportTests(PostgresFixture postgres) : IAsyncLifetime
{
    private const string Admin = "/api/factory/v1/admin";
    private static CancellationToken Ct => TestContext.Current.CancellationToken;
    private FactoryHarness _f = null!;

    public async ValueTask InitializeAsync()
    {
        Assert.SkipUnless(FfmpegAvailable(), "ffmpeg is not installed.");
        _f = await FactoryHarness.StartAsync(postgres);
    }

    public async ValueTask DisposeAsync()
    {
        if (_f is not null)
        {
            await _f.DisposeAsync();
        }
    }

    private static bool FfmpegAvailable()
    {
        try
        {
            using var process = Process.Start(new ProcessStartInfo("ffmpeg", "-version") { RedirectStandardOutput = true, RedirectStandardError = true });
            process?.WaitForExit(10_000);
            return process?.ExitCode == 0;
        }
        catch (System.ComponentModel.Win32Exception)
        {
            return false;
        }
    }

    private async Task ImportAsync()
    {
        (await _f.Admin.PostAsJsonAsync($"{Admin}/snapshot-imports", new { destination = "marseille" }, Ct)).EnsureSuccessStatusCode();
        await Task.Delay(300, Ct);
        await _f.WaitForQueueDrainAsync();
    }

    private async Task<JsonElement> CatalogPoiAsync(string slug) => await _f.Traveler.GetFromJsonAsync<JsonElement>($"/api/catalog/v1/pois/{slug}", Ct);

    private async Task WaitForCatalogAsync(int pois, int stories) =>
        (await FactoryHarness.EventuallyAsync(async () =>
            await _f.CountAsync("select count(*) from catalog.poi") == pois && await _f.CountAsync("select count(*) from catalog.story where status = 'published'") == stories))
            .ShouldBeTrue($"the catalog did not reach {pois} places and {stories} published stories");

    [Fact]
    public async Task Import_publishes_places_and_voiced_stories_to_the_catalog_and_a_second_import_changes_nothing()
    {
        await ImportAsync();
        await WaitForCatalogAsync(3, 3);

        var poi = await CatalogPoiAsync("vieux-port");
        poi.GetProperty("name").GetString().ShouldBe("Vieux-Port");
        var story = poi.GetProperty("stories")[0];
        story.GetProperty("aiGenerated").GetBoolean().ShouldBeTrue("a snapshot story is an AI draft and must be flagged as such");
        story.GetProperty("audioUrl").GetString()!.ShouldContain("/media/audio/");
        story.GetProperty("text").GetString()!.ShouldContain("texte de test");
        poi.GetProperty("attributions").EnumerateArray().Select(item => item.GetString()).ShouldContain("Vieux-Port de Marseille — Wikipédia — CC BY-SA 4.0");
        poi.GetProperty("links").EnumerateArray().Select(link => link.GetProperty("url").GetString()).ShouldContain("https://fr.wikipedia.org/wiki/Vieux-Port_de_Marseille");

        // The five audio parts exist on disk, tagged as AI generated by the normal audio chain.
        (await _f.CountAsync("select count(*) from factory.story_audio_part")).ShouldBe(15);
        Directory.EnumerateFiles(_f.MediaDirectory, "*main.mp3", SearchOption.AllDirectories).Count().ShouldBe(3);

        // Ethics and scores survive the trip: Callelongue is fragile and a hidden gem.
        var nearby = await _f.Traveler.GetFromJsonAsync<JsonElement>("/api/catalog/v1/destinations/marseille/pois?lat=43.2105&lon=5.3520&radius=500", Ct);
        var callelongue = nearby.EnumerateArray().Single();
        callelongue.GetProperty("fragile").GetBoolean().ShouldBeTrue();
        callelongue.GetProperty("hiddenGem").GetBoolean().ShouldBeTrue();

        // Idempotent: nothing is republished, no version moves, no audio is made twice.
        var speechCalls = _f.Content.Speech.Requests.Count;
        await ImportAsync();
        _f.Content.Speech.Requests.Count.ShouldBe(speechCalls);
        (await _f.CountAsync("select count(*) from factory.story")).ShouldBe(3);
        (await _f.CountAsync("select count(*) from factory.place where published_version <> 1")).ShouldBe(0);
        (await _f.CountAsync("select count(*) from factory.place where source = 'snapshot'")).ShouldBe(3);
    }

    [Fact]
    public async Task A_changed_story_becomes_a_new_version_and_the_old_one_is_archived()
    {
        await ImportAsync();
        await WaitForCatalogAsync(3, 3);

        var path = Path.Combine(_f.SnapshotDirectory, "marseille", "pois.json");
        var pois = JsonNode.Parse(await File.ReadAllTextAsync(path, Ct))!.AsArray();
        pois[0]!["story"]!["text"] = "Un texte corrigé après relecture humaine, avec une première phrase. Puis une seconde phrase, pour le rythme.";
        await File.WriteAllTextAsync(path, pois.ToJsonString(), Ct);

        await ImportAsync();
        (await FactoryHarness.EventuallyAsync(async () => await _f.CountAsync("select count(*) from catalog.story where status = 'archived'") == 1)).ShouldBeTrue("the old version was not archived");

        (await _f.CountAsync("select count(*) from factory.story")).ShouldBe(4);
        (await _f.QueryAsync("select count(*) from factory.story where version = 2 and status = 'Published'", r => r.GetInt64(0))).ShouldBe(1);
        var changed = await CatalogPoiAsync(pois[0]!["slug"]!.GetValue<string>());
        changed.GetProperty("stories").GetArrayLength().ShouldBe(1);
        changed.GetProperty("stories")[0].GetProperty("text").GetString()!.ShouldContain("corrigé après relecture");
    }

    [Fact]
    public async Task Without_a_voice_stories_are_published_as_text_only_then_get_audio_in_a_new_version_when_a_voice_exists()
    {
        _f.Content.Speech.Available = false;
        await ImportAsync();
        await WaitForCatalogAsync(3, 3);

        var textOnly = (await CatalogPoiAsync("fort-saint-jean")).GetProperty("stories")[0];
        textOnly.GetProperty("text").GetString().ShouldNotBeNullOrWhiteSpace();
        textOnly.GetProperty("audioUrl").ValueKind.ShouldBe(JsonValueKind.Null);
        (await _f.CountAsync("select count(*) from factory.story_audio_part")).ShouldBe(0);
        _f.Content.Speech.Requests.ShouldBeEmpty();

        _f.Content.Speech.Available = true;
        await ImportAsync();
        (await FactoryHarness.EventuallyAsync(async () => await _f.CountAsync("select count(*) from catalog.story where status = 'published' and audio_path is not null") == 3)).ShouldBeTrue("the voiced versions did not reach the catalog");

        (await _f.CountAsync("select count(*) from factory.story where version = 2 and status = 'Published'")).ShouldBe(3);
        (await CatalogPoiAsync("fort-saint-jean")).GetProperty("stories")[0].GetProperty("audioUrl").GetString().ShouldNotBeNull();
    }

    [Fact]
    public async Task A_place_an_editor_unpublished_is_not_published_again_by_a_new_import()
    {
        await ImportAsync();
        await WaitForCatalogAsync(3, 3);
        var id = await _f.QueryAsync("select id from factory.place where slug = 'callelongue'", r => r.GetGuid(0));

        (await _f.Admin.PostAsJsonAsync($"{Admin}/places/{id}/unpublish", new { reason = "test" }, Ct)).EnsureSuccessStatusCode();
        await _f.WaitForQueueDrainAsync();
        await ImportAsync();

        (await _f.QueryAsync("select status from factory.place where slug = 'callelongue'", r => r.GetString(0))).ShouldBe("Unpublished");
    }
}
