// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using OnVoyage.Catalog.Infrastructure.Persistence;

#nullable disable

namespace OnVoyage.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20261001070737_ConfigSnapshot")]
    partial class ConfigSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.ConfigSnapshotRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Key");

                    b.ToTable("config_snapshot", "catalog");
                });

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.DestinationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Point>("Center")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("center");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_fr");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("destination", "catalog");
                });

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.PoiEthicsRow", b =>
                {
                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<bool>("AccessRegulated")
                        .HasColumnType("boolean")
                        .HasColumnName("access_regulated");

                    b.Property<bool>("Fragile")
                        .HasColumnType("boolean")
                        .HasColumnName("fragile");

                    b.HasKey("PoiId");

                    b.ToTable("poi_ethics", "catalog");
                });

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.PoiInterestRow", b =>
                {
                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<string>("TaxonomyCode")
                        .HasColumnType("text")
                        .HasColumnName("taxonomy_code");

                    b.Property<float>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.HasKey("PoiId", "TaxonomyCode");

                    b.HasIndex("TaxonomyCode");

                    b.ToTable("poi_interest", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_poi_interest_weight", "weight > 0 and weight <= 1");
                        });
                });

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.PoiRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float>("ContentQualityScore")
                        .HasColumnType("real")
                        .HasColumnName("content_quality_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<bool>("HiddenGem")
                        .HasColumnType("boolean")
                        .HasColumnName("hidden_gem");

                    b.Property<short>("ImportanceScore")
                        .HasColumnType("smallint")
                        .HasColumnName("importance_score");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("TaxonomyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("taxonomy_version");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("DestinationId", "Slug")
                        .IsUnique();

                    b.ToTable("poi", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_poi_importance", "importance_score between 0 and 100");
                        });
                });

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.PoiTextRow", b =>
                {
                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<string>("Lang")
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "french")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Name", "ShortDescription" });

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text")
                        .HasColumnName("short_description");

                    b.HasKey("PoiId", "Lang");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.ToTable("poi_text", "catalog");
                });

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.StoryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AudioPath")
                        .HasColumnType("text")
                        .HasColumnName("audio_path");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ai_generated");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PoiId", "Lang")
                        .HasDatabaseName("ix_story_current_published")
                        .HasFilter("status = 'published'");

                    b.HasIndex("PoiId", "Lang", "Kind", "Version")
                        .IsUnique();

                    b.ToTable("story", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_story_premium_text", "not is_premium or text is null");

                            t.HasCheckConstraint("ck_story_status", "status in ('published', 'unpublished', 'archived')");
                        });
                });

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.TaxonomyNodeRow", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("ParentCode")
                        .HasColumnType("text")
                        .HasColumnName("parent_code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("TaxonomyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("taxonomy_version");

                    b.HasKey("Code");

                    b.ToTable("taxonomy_node", "catalog");
                });

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.PoiEthicsRow", b =>
                {
                    b.HasOne("OnVoyage.Catalog.Infrastructure.Persistence.PoiRow", null)
                        .WithOne("Ethics")
                        .HasForeignKey("OnVoyage.Catalog.Infrastructure.Persistence.PoiEthicsRow", "PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OnVoyage.Catalog.Infrastructure.Persistence.CrowdProfileJson", "CrowdProfile", b1 =>
                        {
                            b1.Property<Guid>("PoiEthicsRowPoiId");

                            b1.Property<short>("Offpeak")
                                .HasJsonPropertyName("offpeak");

                            b1.Property<short>("Peak")
                                .HasJsonPropertyName("peak");

                            b1.Property<short>("Shoulder")
                                .HasJsonPropertyName("shoulder");

                            b1.HasKey("PoiEthicsRowPoiId");

                            b1.ToTable("poi_ethics", "catalog");

                            b1
                                .ToJson("crowd_profile")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PoiEthicsRowPoiId");
                        });

                    b.Navigation("CrowdProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.PoiInterestRow", b =>
                {
                    b.HasOne("OnVoyage.Catalog.Infrastructure.Persistence.PoiRow", null)
                        .WithMany("Interests")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnVoyage.Catalog.Infrastructure.Persistence.TaxonomyNodeRow", null)
                        .WithMany()
                        .HasForeignKey("TaxonomyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.PoiRow", b =>
                {
                    b.HasOne("OnVoyage.Catalog.Infrastructure.Persistence.DestinationRow", "Destination")
                        .WithMany("Pois")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.PoiTextRow", b =>
                {
                    b.HasOne("OnVoyage.Catalog.Infrastructure.Persistence.PoiRow", null)
                        .WithMany("Texts")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.StoryRow", b =>
                {
                    b.HasOne("OnVoyage.Catalog.Infrastructure.Persistence.PoiRow", null)
                        .WithMany("Stories")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.DestinationRow", b =>
                {
                    b.Navigation("Pois");
                });

            modelBuilder.Entity("OnVoyage.Catalog.Infrastructure.Persistence.PoiRow", b =>
                {
                    b.Navigation("Ethics");

                    b.Navigation("Interests");

                    b.Navigation("Stories");

                    b.Navigation("Texts");
                });
#pragma warning restore 612, 618
        }
    }
}
