// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnVoyage.Insights.Infrastructure.Persistence;

#nullable disable

namespace OnVoyage.Insights.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InsightsDbContext))]
    [Migration("20261001144636_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("insights")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnVoyage.Insights.Infrastructure.Persistence.ConfigSnapshotRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Key");

                    b.ToTable("config_snapshot", "insights");
                });

            modelBuilder.Entity("OnVoyage.Insights.Infrastructure.Persistence.ConsentProjectionRow", b =>
                {
                    b.Property<Guid>("TravelerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<bool>("Analytics")
                        .HasColumnType("boolean")
                        .HasColumnName("analytics");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TravelerId");

                    b.ToTable("consent_projection", "insights");
                });

            modelBuilder.Entity("OnVoyage.Insights.Infrastructure.Persistence.DailyKpiRow", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("DestinationId")
                        .HasColumnType("text")
                        .HasColumnName("destination_id");

                    b.Property<string>("Cohort")
                        .HasColumnType("text")
                        .HasColumnName("cohort");

                    b.Property<string>("Metric")
                        .HasColumnType("text")
                        .HasColumnName("metric");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Date", "DestinationId", "Cohort", "Metric");

                    b.ToTable("daily_kpi", "insights");
                });

            modelBuilder.Entity("OnVoyage.Insights.Infrastructure.Persistence.EventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("Props")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("props");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("TravelerRef")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_ref");

                    b.HasKey("Id", "OccurredAt");

                    b.HasIndex("Name", "OccurredAt");

                    b.HasIndex("TravelerRef", "OccurredAt");

                    b.ToTable("event", "insights");
                });
#pragma warning restore 612, 618
        }
    }
}
