<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="FluentValidation" />
    <ProjectReference Include="../OnVoyage.Factory.Domain/OnVoyage.Factory.Domain.csproj" />
    <ProjectReference Include="../OnVoyage.Factory.Contracts/OnVoyage.Factory.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Factory.UnitTests" />
  </ItemGroup>
</Project>
