<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <ProjectReference Include="../../../Aspire/OnVoyage.ServiceDefaults/OnVoyage.ServiceDefaults.csproj" />
    <ProjectReference Include="../OnVoyage.Discovery.Application/OnVoyage.Discovery.Application.csproj" />
    <ProjectReference Include="../OnVoyage.Discovery.Domain/OnVoyage.Discovery.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Discovery.UnitTests" />
    <InternalsVisibleTo Include="Discovery.IntegrationTests" />
  </ItemGroup>
</Project>
