// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnVoyage.Discovery.Infrastructure.Persistence;

#nullable disable

namespace OnVoyage.Discovery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DiscoveryDbContext))]
    [Migration("20261002074700_CollaborativeScores")]
    partial class CollaborativeScores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("discovery")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.CategoryAffinityRow", b =>
                {
                    b.Property<string>("CodeA")
                        .HasColumnType("text")
                        .HasColumnName("code_a");

                    b.Property<string>("CodeB")
                        .HasColumnType("text")
                        .HasColumnName("code_b");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<double>("Lift")
                        .HasColumnType("double precision")
                        .HasColumnName("lift");

                    b.HasKey("CodeA", "CodeB");

                    b.ToTable("category_affinity", "discovery");
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.CfScoreRow", b =>
                {
                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<float>("Score")
                        .HasColumnType("real")
                        .HasColumnName("score");

                    b.Property<int>("Support")
                        .HasColumnType("integer")
                        .HasColumnName("support");

                    b.HasKey("TravelerId", "PoiId");

                    b.HasIndex("TravelerId", "Destination");

                    b.ToTable("cf_score", "discovery", t =>
                        {
                            t.HasCheckConstraint("ck_cf_score_range", "score between -1 and 1 and support > 0");
                        });
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.CreatorFollowRow", b =>
                {
                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<bool>("Following")
                        .HasColumnType("boolean")
                        .HasColumnName("following");

                    b.HasKey("TravelerId", "CreatorId");

                    b.ToTable("creator_follow", "discovery");
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.CreatorPlaceLinkRow", b =>
                {
                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id");

                    b.Property<bool>("IsCommercial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_commercial");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<bool>("Validated")
                        .HasColumnType("boolean")
                        .HasColumnName("validated");

                    b.HasKey("CreatorId", "PoiId", "ContentId");

                    b.HasIndex("PoiId");

                    b.ToTable("creator_place_link", "discovery");
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.CreatorProjectionRow", b =>
                {
                    b.Property<Guid>("CreatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("text")
                        .HasColumnName("avatar_path");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handle");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Specialties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("specialties");

                    b.Property<string>("Vector")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("vector");

                    b.HasKey("CreatorId");

                    b.ToTable("creator_projection", "discovery");
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.ImpressionRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ClientEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_event_id");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<DateTimeOffset>("ShownAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shown_at");

                    b.Property<string>("Surface")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surface");

                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.HasKey("Id");

                    b.HasIndex("ShownAt");

                    b.HasIndex("TravelerId", "ClientEventId")
                        .IsUnique();

                    b.ToTable("impression", "discovery");
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.InteractionRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryCode")
                        .HasColumnType("text")
                        .HasColumnName("category_code");

                    b.Property<Guid>("ClientEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_event_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<Guid?>("StoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.Property<int?>("StoryVersion")
                        .HasColumnType("integer")
                        .HasColumnName("story_version");

                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.Property<string>("Weights")
                        .HasColumnType("jsonb")
                        .HasColumnName("weights");

                    b.HasKey("Id");

                    b.HasIndex("TravelerId", "ClientEventId")
                        .IsUnique();

                    b.HasIndex("TravelerId", "OccurredAt");

                    b.ToTable("interaction", "discovery");
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.InterestVectorRow", b =>
                {
                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<string>("Locks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("locks");

                    b.Property<int>("TaxonomyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("taxonomy_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<float[]>("Vector")
                        .IsRequired()
                        .HasColumnType("real[]")
                        .HasColumnName("vector");

                    b.HasKey("TravelerId");

                    b.ToTable("interest_vector", "discovery");
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.OnboardingClipRow", b =>
                {
                    b.Property<Guid>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("AudioPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("audio_path");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("StoryId");

                    b.HasIndex("Lang");

                    b.ToTable("onboarding_clip", "discovery");
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.PoiProjectionRow", b =>
                {
                    b.Property<Guid>("PoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<bool>("AccessRegulated")
                        .HasColumnType("boolean")
                        .HasColumnName("access_regulated");

                    b.Property<int>("CrowdLevel")
                        .HasColumnType("integer")
                        .HasColumnName("crowd_level");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<bool>("Fragile")
                        .HasColumnType("boolean")
                        .HasColumnName("fragile");

                    b.Property<bool>("HiddenGem")
                        .HasColumnType("boolean")
                        .HasColumnName("hidden_gem");

                    b.Property<double>("Importance")
                        .HasColumnType("double precision")
                        .HasColumnName("importance");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("Quality")
                        .HasColumnType("double precision")
                        .HasColumnName("quality");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Weights")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("weights");

                    b.HasKey("PoiId");

                    b.ToTable("poi_projection", "discovery");
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.PoiRatingRow", b =>
                {
                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<bool>("Excluded")
                        .HasColumnType("boolean")
                        .HasColumnName("excluded");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TravelerId", "PoiId");

                    b.ToTable("poi_rating", "discovery");
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.SavedPoiRow", b =>
                {
                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<DateTimeOffset>("SavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at");

                    b.HasKey("TravelerId", "PoiId");

                    b.ToTable("saved_poi", "discovery");
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.StoryProjectionRow", b =>
                {
                    b.Property<Guid>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.Property<string>("AudioParts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("audio_parts");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("StoryId");

                    b.HasIndex("PoiId");

                    b.ToTable("story_projection", "discovery");
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.TravelerRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cohort")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cohort");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EthicalMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ethical_mode");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<int>("ProfileDepth")
                        .HasColumnType("integer")
                        .HasColumnName("profile_depth");

                    b.HasKey("Id");

                    b.ToTable("traveler", "discovery", t =>
                        {
                            t.HasCheckConstraint("ck_traveler_cohort", "cohort in ('control', 'personalized')");
                        });
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.VisitRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ClientEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_event_id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<int>("DwellS")
                        .HasColumnType("integer")
                        .HasColumnName("dwell_s");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<DateOnly>("VisitedOn")
                        .HasColumnType("date")
                        .HasColumnName("visited_on");

                    b.HasKey("Id");

                    b.HasIndex("TravelerId", "ClientEventId")
                        .IsUnique();

                    b.ToTable("visit", "discovery");
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.CfScoreRow", b =>
                {
                    b.HasOne("OnVoyage.Discovery.Infrastructure.Persistence.TravelerRow", null)
                        .WithMany()
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.CreatorFollowRow", b =>
                {
                    b.HasOne("OnVoyage.Discovery.Infrastructure.Persistence.TravelerRow", null)
                        .WithMany()
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.ImpressionRow", b =>
                {
                    b.HasOne("OnVoyage.Discovery.Infrastructure.Persistence.TravelerRow", null)
                        .WithMany()
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.InteractionRow", b =>
                {
                    b.HasOne("OnVoyage.Discovery.Infrastructure.Persistence.TravelerRow", null)
                        .WithMany()
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.InterestVectorRow", b =>
                {
                    b.HasOne("OnVoyage.Discovery.Infrastructure.Persistence.TravelerRow", null)
                        .WithOne()
                        .HasForeignKey("OnVoyage.Discovery.Infrastructure.Persistence.InterestVectorRow", "TravelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.PoiRatingRow", b =>
                {
                    b.HasOne("OnVoyage.Discovery.Infrastructure.Persistence.TravelerRow", null)
                        .WithMany()
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.SavedPoiRow", b =>
                {
                    b.HasOne("OnVoyage.Discovery.Infrastructure.Persistence.TravelerRow", null)
                        .WithMany()
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Discovery.Infrastructure.Persistence.VisitRow", b =>
                {
                    b.HasOne("OnVoyage.Discovery.Infrastructure.Persistence.TravelerRow", null)
                        .WithMany()
                        .HasForeignKey("TravelerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
