<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="bunit" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <ProjectReference Include="../../src/Web/OnVoyage.Web.Admin/OnVoyage.Web.Admin.csproj" />
  </ItemGroup>
</Project>
