<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
    <ProjectReference Include="../OnVoyage.UI.Components/OnVoyage.UI.Components.csproj" />
    <ProjectReference Include="../../Mobile/OnVoyage.App.Infrastructure/OnVoyage.App.Infrastructure.csproj" />
    <ServiceWorker Include="wwwroot/service-worker.js" PublishedContent="wwwroot/service-worker.published.js" />
  </ItemGroup>
</Project>
