// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnVoyage.Creators.Infrastructure.Persistence;

#nullable disable

namespace OnVoyage.Creators.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CreatorsDbContext))]
    partial class CreatorsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("creators")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnVoyage.Creators.Infrastructure.Persistence.ContentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CaptionExcerpt")
                        .HasColumnType("text")
                        .HasColumnName("caption_excerpt");

                    b.Property<string>("Chapters")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("chapters");

                    b.Property<string>("CoverPath")
                        .HasColumnType("text")
                        .HasColumnName("cover_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<int?>("DurationS")
                        .HasColumnType("integer")
                        .HasColumnName("duration_s");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<bool>("IsCommercial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_commercial");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Permalink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permalink");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Platform", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_content_item_platform_external_id");

                    b.ToTable("content_item", "creators", t =>
                        {
                            t.HasCheckConstraint("ck_content_item_excerpt", "char_length(caption_excerpt) <= 500");

                            t.HasCheckConstraint("ck_content_item_kind", "kind in ('video', 'photo', 'carousel', 'article')");

                            t.HasCheckConstraint("ck_content_item_platform", "platform in ('instagram', 'youtube', 'tiktok')");

                            t.HasCheckConstraint("ck_content_item_status", "status in ('imported', 'hidden', 'removed')");
                        });
                });

            modelBuilder.Entity("OnVoyage.Creators.Infrastructure.Persistence.CreatorRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("text")
                        .HasColumnName("avatar_path");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<Guid[]>("DestinationIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("destination_ids");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("Founding")
                        .HasColumnType("boolean")
                        .HasColumnName("founding");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("citext")
                        .HasColumnName("handle");

                    b.PrimitiveCollection<string[]>("Languages")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("languages");

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("links");

                    b.PrimitiveCollection<string[]>("Specialties")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("specialties");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terms_accepted_at");

                    b.Property<string>("TermsDocumentRef")
                        .HasColumnType("text")
                        .HasColumnName("terms_document_ref");

                    b.Property<string>("TermsVersion")
                        .HasColumnType("text")
                        .HasColumnName("terms_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_creator_account")
                        .HasFilter("account_id is not null");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasDatabaseName("ux_creator_handle");

                    b.HasIndex("Status");

                    b.ToTable("creator", "creators", t =>
                        {
                            t.HasCheckConstraint("ck_creator_status", "status in ('draft', 'published', 'suspended')");
                        });
                });

            modelBuilder.Entity("OnVoyage.Creators.Infrastructure.Persistence.FollowRow", b =>
                {
                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTimeOffset>("FollowedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("followed_at");

                    b.HasKey("TravelerId", "CreatorId");

                    b.HasIndex("CreatorId");

                    b.ToTable("follow", "creators");
                });

            modelBuilder.Entity("OnVoyage.Creators.Infrastructure.Persistence.ModerationCaseRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("Decision")
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReporterRef")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_ref");

                    b.Property<string>("StatementOfReasons")
                        .HasColumnType("text")
                        .HasColumnName("statement_of_reasons");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("ReporterRef");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("TargetType", "TargetId");

                    b.ToTable("moderation_case", "creators", t =>
                        {
                            t.HasCheckConstraint("ck_moderation_case_status", "status in ('open', 'decided')");

                            t.HasCheckConstraint("ck_moderation_case_target", "target_type in ('creator', 'content', 'place_link', 'tip')");
                        });
                });

            modelBuilder.Entity("OnVoyage.Creators.Infrastructure.Persistence.PlaceLinkRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<Guid?>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<string>("Signals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("signals");

                    b.Property<int?>("StartS")
                        .HasColumnType("integer")
                        .HasColumnName("start_s");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("PoiId", "Status");

                    b.HasIndex("CreatorId", "PoiId", "ContentId", "StartS")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("CreatorId", "PoiId", "ContentId", "StartS"), false);

                    b.ToTable("place_link", "creators", t =>
                        {
                            t.HasCheckConstraint("ck_place_link_status", "status in ('proposed', 'validated', 'rejected')");
                        });
                });

            modelBuilder.Entity("OnVoyage.Creators.Infrastructure.Persistence.PoiDirectoryRow", b =>
                {
                    b.Property<Guid>("PoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<string>("DestinationSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_slug");

                    b.Property<short>("ImportanceScore")
                        .HasColumnType("smallint")
                        .HasColumnName("importance_score");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("names");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("PoiId");

                    b.HasIndex("DestinationSlug");

                    b.HasIndex("SearchText");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchText"), new[] { "gin_trgm_ops" });

                    b.ToTable("poi_directory", "creators");
                });

            modelBuilder.Entity("OnVoyage.Creators.Infrastructure.Persistence.TipRow", b =>
                {
                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid>("PoiId")
                        .HasColumnType("uuid")
                        .HasColumnName("poi_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CreatorId", "PoiId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("creator_tip", "creators", t =>
                        {
                            t.HasCheckConstraint("ck_creator_tip_status", "status in ('published', 'hidden')");

                            t.HasCheckConstraint("ck_creator_tip_text", "char_length(\"text\") <= 280");
                        });
                });

            modelBuilder.Entity("OnVoyage.Creators.Infrastructure.Persistence.ContentRow", b =>
                {
                    b.HasOne("OnVoyage.Creators.Infrastructure.Persistence.CreatorRow", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Creators.Infrastructure.Persistence.FollowRow", b =>
                {
                    b.HasOne("OnVoyage.Creators.Infrastructure.Persistence.CreatorRow", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Creators.Infrastructure.Persistence.PlaceLinkRow", b =>
                {
                    b.HasOne("OnVoyage.Creators.Infrastructure.Persistence.ContentRow", null)
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnVoyage.Creators.Infrastructure.Persistence.CreatorRow", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Creators.Infrastructure.Persistence.TipRow", b =>
                {
                    b.HasOne("OnVoyage.Creators.Infrastructure.Persistence.CreatorRow", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
