<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <ProjectReference Include="../OnVoyage.Platform.Application/OnVoyage.Platform.Application.csproj" />
    <ProjectReference Include="../OnVoyage.Platform.Domain/OnVoyage.Platform.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Seed/default-config.json" LogicalName="default-config.json" />
    <InternalsVisibleTo Include="Platform.UnitTests" />
    <InternalsVisibleTo Include="Platform.IntegrationTests" />
  </ItemGroup>
</Project>
