<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="FluentValidation" />
    <ProjectReference Include="../OnVoyage.Catalog.Domain/OnVoyage.Catalog.Domain.csproj" />
    <ProjectReference Include="../OnVoyage.Catalog.Contracts/OnVoyage.Catalog.Contracts.csproj" />
    <ProjectReference Include="../../Platform/OnVoyage.Platform.Contracts/OnVoyage.Platform.Contracts.csproj" />
    <ProjectReference Include="../../Factory/OnVoyage.Factory.Contracts/OnVoyage.Factory.Contracts.csproj" />
  </ItemGroup>
</Project>
