<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
    <ProjectReference Include="../OnVoyage.Catalog.Application/OnVoyage.Catalog.Application.csproj" />
    <ProjectReference Include="../OnVoyage.Catalog.Infrastructure/OnVoyage.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="../OnVoyage.Catalog.Contracts/OnVoyage.Catalog.Contracts.csproj" />
    <ProjectReference Include="../../../Aspire/OnVoyage.ServiceDefaults/OnVoyage.ServiceDefaults.csproj" />
    <ProjectReference Include="../../../Shared/OnVoyage.Messaging/OnVoyage.Messaging.csproj" />
  </ItemGroup>
</Project>
