<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <ProjectReference Include="../../OnVoyage.TestInfrastructure/OnVoyage.TestInfrastructure.csproj" />
    <ProjectReference Include="../../../src/Services/Insights/OnVoyage.Insights.Api/OnVoyage.Insights.Api.csproj" />
    <ProjectReference Include="../../../src/Services/Insights/OnVoyage.Insights.Infrastructure/OnVoyage.Insights.Infrastructure.csproj" />
  </ItemGroup>
</Project>
