<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <ProjectReference Include="../../src/Aspire/OnVoyage.ServiceDefaults/OnVoyage.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
