// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnVoyage.Factory.Infrastructure.Persistence;

#nullable disable

namespace OnVoyage.Factory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FactoryDbContext))]
    partial class FactoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("factory")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.AuditLogRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("audit_log", "factory");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.BootstrapRunRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoPublish")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_publish");

                    b.Property<double>("BudgetUsd")
                        .HasColumnType("double precision")
                        .HasColumnName("budget_usd");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_requested");

                    b.Property<double>("CostUsd")
                        .HasColumnType("double precision")
                        .HasColumnName("cost_usd");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("Failed")
                        .HasColumnType("integer")
                        .HasColumnName("failed");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<int>("MaxPlaces")
                        .HasColumnType("integer")
                        .HasColumnName("max_places");

                    b.Property<int?>("MinImportance")
                        .HasColumnType("integer")
                        .HasColumnName("min_importance");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<int>("PlacesDone")
                        .HasColumnType("integer")
                        .HasColumnName("places_done");

                    b.Property<int>("PlacesTotal")
                        .HasColumnType("integer")
                        .HasColumnName("places_total");

                    b.Property<int>("Published")
                        .HasColumnType("integer")
                        .HasColumnName("published");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requested_by");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("steps");

                    b.Property<int>("ToReview")
                        .HasColumnType("integer")
                        .HasColumnName("to_review");

                    b.Property<int>("Written")
                        .HasColumnType("integer")
                        .HasColumnName("written");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAt");

                    b.ToTable("bootstrap_run", "factory");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.DedupLinkRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Automatic")
                        .HasColumnType("boolean")
                        .HasColumnName("automatic");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_meters");

                    b.Property<string>("InheritedQid")
                        .HasColumnType("text")
                        .HasColumnName("inherited_qid");

                    b.Property<Guid>("KeptPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("kept_place_id");

                    b.Property<Guid>("OtherPlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("other_place_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("RevertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reverted_at");

                    b.Property<double>("Similarity")
                        .HasColumnType("double precision")
                        .HasColumnName("similarity");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("KeptPlaceId");

                    b.HasIndex("OtherPlaceId");

                    b.ToTable("dedup_link", "factory");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.FactRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("PlaceId");

                    b.ToTable("fact", "factory", t =>
                        {
                            t.HasCheckConstraint("ck_fact_confidence", "confidence between 0 and 1");
                        });
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.GenerationBatchRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Criteria")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("criteria");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("generation_batch", "factory");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.GenerationJobRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("place_name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step");

                    b.Property<Guid?>("StoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "State");

                    b.ToTable("generation_job", "factory", t =>
                        {
                            t.HasCheckConstraint("ck_generation_job_state", "state in ('Pending', 'Running', 'Succeeded', 'Failed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.ImportRunRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Created")
                        .HasColumnType("integer")
                        .HasColumnName("created");

                    b.Property<string>("DestinationSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_slug");

                    b.Property<int>("RawRows")
                        .HasColumnType("integer")
                        .HasColumnName("raw_rows");

                    b.Property<string>("RawTable")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_table");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Updated")
                        .HasColumnType("integer")
                        .HasColumnName("updated");

                    b.HasKey("Id");

                    b.ToTable("import_run", "factory");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.LlmCallRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContentId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_id");

                    b.Property<double>("CostUsd")
                        .HasColumnType("double precision")
                        .HasColumnName("cost_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("PromptId")
                        .HasColumnType("text")
                        .HasColumnName("prompt_id");

                    b.Property<string>("PromptVersion")
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("succeeded");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("llm_call", "factory");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.PageviewsRow", b =>
                {
                    b.Property<string>("Qid")
                        .HasColumnType("text")
                        .HasColumnName("qid");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("SourceLicense")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_license");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<long>("Views12Months")
                        .HasColumnType("bigint")
                        .HasColumnName("views12_months");

                    b.HasKey("Qid", "Language");

                    b.ToTable("wikipedia_pageviews", "factory_raw");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.PlaceInterestRow", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("TaxonomyCode")
                        .HasColumnType("text")
                        .HasColumnName("taxonomy_code");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<float>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.HasKey("PlaceId", "TaxonomyCode");

                    b.ToTable("place_interest", "factory", t =>
                        {
                            t.HasCheckConstraint("ck_place_interest_weight", "weight > 0 and weight <= 1");
                        });
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.PlaceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AccessRegulated")
                        .HasColumnType("boolean")
                        .HasColumnName("access_regulated");

                    b.Property<long>("AnnualPageviews")
                        .HasColumnType("bigint")
                        .HasColumnName("annual_pageviews");

                    b.Property<float>("ClassificationConfidence")
                        .HasColumnType("real")
                        .HasColumnName("classification_confidence");

                    b.Property<string>("ClassificationOutcome")
                        .HasColumnType("text")
                        .HasColumnName("classification_outcome");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("CrowdOffpeak")
                        .HasColumnType("smallint")
                        .HasColumnName("crowd_offpeak");

                    b.Property<short>("CrowdPeak")
                        .HasColumnType("smallint")
                        .HasColumnName("crowd_peak");

                    b.Property<short>("CrowdShoulder")
                        .HasColumnType("smallint")
                        .HasColumnName("crowd_shoulder");

                    b.Property<string>("DestinationSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_slug");

                    b.Property<bool>("EditoriallySaturated")
                        .HasColumnType("boolean")
                        .HasColumnName("editorially_saturated");

                    b.Property<MultiPolygon>("Footprint")
                        .HasColumnType("geometry (multipolygon, 4326)")
                        .HasColumnName("footprint");

                    b.Property<bool>("Fragile")
                        .HasColumnType("boolean")
                        .HasColumnName("fragile");

                    b.Property<bool>("HiddenGem")
                        .HasColumnType("boolean")
                        .HasColumnName("hidden_gem");

                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_run_id");

                    b.Property<short?>("ImportanceOverride")
                        .HasColumnType("smallint")
                        .HasColumnName("importance_override");

                    b.Property<short?>("ImportanceScore")
                        .HasColumnType("smallint")
                        .HasColumnName("importance_score");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<Guid?>("MergedInto")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<long>("OsmId")
                        .HasColumnType("bigint")
                        .HasColumnName("osm_id");

                    b.Property<string>("OsmTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("osm_tags");

                    b.Property<string>("OsmType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("osm_type");

                    b.Property<int?>("OsmVersion")
                        .HasColumnType("integer")
                        .HasColumnName("osm_version");

                    b.Property<short?>("PopularityPercentile")
                        .HasColumnType("smallint")
                        .HasColumnName("popularity_percentile");

                    b.Property<int>("PublishedVersion")
                        .HasColumnType("integer")
                        .HasColumnName("published_version");

                    b.Property<string>("Qid")
                        .HasColumnType("text")
                        .HasColumnName("qid");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceLicense")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_license");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Qid");

                    b.HasIndex("DestinationSlug", "Slug")
                        .IsUnique();

                    b.HasIndex("DestinationSlug", "Status");

                    b.HasIndex("OsmType", "OsmId")
                        .IsUnique();

                    b.ToTable("place", "factory", t =>
                        {
                            t.HasCheckConstraint("ck_place_crowd", "crowd_offpeak between 1 and 5 and crowd_shoulder between 1 and 5 and crowd_peak between 1 and 5");

                            t.HasCheckConstraint("ck_place_importance", "importance_score is null or importance_score between 0 and 100");
                        });
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.PlaceVideoRow", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("VideoId")
                        .HasColumnType("text")
                        .HasColumnName("video_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("SelectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("selected_at");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("PlaceId", "VideoId");

                    b.ToTable("place_video", "factory");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.PronunciationRow", b =>
                {
                    b.Property<string>("DestinationSlug")
                        .HasColumnType("text")
                        .HasColumnName("destination_slug");

                    b.Property<string>("Term")
                        .HasColumnType("text")
                        .HasColumnName("term");

                    b.Property<string>("Replacement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("replacement");

                    b.HasKey("DestinationSlug", "Term");

                    b.ToTable("pronunciation", "factory");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.SourceDocumentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("Publisher")
                        .HasColumnType("text")
                        .HasColumnName("publisher");

                    b.Property<double>("Quality")
                        .HasColumnType("double precision")
                        .HasColumnName("quality");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("Revision")
                        .HasColumnType("text")
                        .HasColumnName("revision");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId", "Url");

                    b.ToTable("source_document", "factory");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.StoryAudioPartRow", b =>
                {
                    b.Property<Guid>("StoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.Property<string>("Part")
                        .HasColumnType("text")
                        .HasColumnName("part");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.HasKey("StoryId", "Part");

                    b.ToTable("story_audio_part", "factory");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.StoryReportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("HandledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handled_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("StoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.Property<Guid>("TravelerId")
                        .HasColumnType("uuid")
                        .HasColumnName("traveler_id");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("StoryId", "TravelerId")
                        .IsUnique();

                    b.HasIndex("TravelerId", "CreatedAt");

                    b.ToTable("story_report", "factory", t =>
                        {
                            t.HasCheckConstraint("ck_story_report_status", "status in ('Open', 'Handled', 'Dismissed')");
                        });
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.StoryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnnounceFront")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("announce_front");

                    b.Property<string>("AnnounceLeft")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("announce_left");

                    b.Property<string>("AnnounceRight")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("announce_right");

                    b.Property<string>("CareNote")
                        .HasColumnType("text")
                        .HasColumnName("care_note");

                    b.Property<string>("CheckReport")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("check_report");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("EditorialScore")
                        .HasColumnType("double precision")
                        .HasColumnName("editorial_score");

                    b.Property<int>("EstimatedDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_duration_seconds");

                    b.PrimitiveCollection<Guid[]>("FactsUsed")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("facts_used");

                    b.Property<string>("Hook")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hook");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<Guid>("PlaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("place_id");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_version");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<double>("QualityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("quality_score");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text")
                        .HasColumnName("rejected_reason");

                    b.Property<string>("RemoteIntro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remote_intro");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("VoiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("voice_id");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId", "Lang", "Kind", "Version")
                        .IsUnique();

                    b.ToTable("story", "factory");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.WikidataEntityRow", b =>
                {
                    b.Property<string>("Qid")
                        .HasColumnType("text")
                        .HasColumnName("qid");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionFr")
                        .HasColumnType("text")
                        .HasColumnName("description_fr");

                    b.PrimitiveCollection<string[]>("HeritageStatuses")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("heritage_statuses");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Inception")
                        .HasColumnType("text")
                        .HasColumnName("inception");

                    b.PrimitiveCollection<string[]>("InstanceOf")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("instance_of");

                    b.Property<string>("LabelEn")
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<string>("LabelFr")
                        .HasColumnType("text")
                        .HasColumnName("label_fr");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<int>("Sitelinks")
                        .HasColumnType("integer")
                        .HasColumnName("sitelinks");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceLicense")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_license");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.Property<string>("WikipediaEn")
                        .HasColumnType("text")
                        .HasColumnName("wikipedia_en");

                    b.Property<string>("WikipediaFr")
                        .HasColumnType("text")
                        .HasColumnName("wikipedia_fr");

                    b.HasKey("Qid");

                    b.ToTable("wikidata_entity", "factory_raw");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.YouTubeSearchRow", b =>
                {
                    b.Property<string>("QueryKey")
                        .HasColumnType("text")
                        .HasColumnName("query_key");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Results")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("results");

                    b.HasKey("QueryKey");

                    b.ToTable("youtube_search", "factory");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.YouTubeUsageRow", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("Units")
                        .HasColumnType("integer")
                        .HasColumnName("units");

                    b.HasKey("Day");

                    b.ToTable("youtube_usage", "factory");
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.PlaceInterestRow", b =>
                {
                    b.HasOne("OnVoyage.Factory.Infrastructure.Persistence.PlaceRow", null)
                        .WithMany("Interests")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnVoyage.Factory.Infrastructure.Persistence.PlaceRow", b =>
                {
                    b.Navigation("Interests");
                });
#pragma warning restore 612, 618
        }
    }
}
