<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <ProjectReference Include="../OnVoyage.Catalog.Application/OnVoyage.Catalog.Application.csproj" />
    <ProjectReference Include="../OnVoyage.Catalog.Domain/OnVoyage.Catalog.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Catalog.UnitTests" />
    <InternalsVisibleTo Include="Catalog.IntegrationTests" />
  </ItemGroup>
</Project>
