<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <ProjectReference Include="../OnVoyage.Factory.Application/OnVoyage.Factory.Application.csproj" />
    <ProjectReference Include="../OnVoyage.Factory.Infrastructure/OnVoyage.Factory.Infrastructure.csproj" />
    <ProjectReference Include="../OnVoyage.Factory.Contracts/OnVoyage.Factory.Contracts.csproj" />
    <ProjectReference Include="../../../Aspire/OnVoyage.ServiceDefaults/OnVoyage.ServiceDefaults.csproj" />
    <ProjectReference Include="../../../Shared/OnVoyage.Messaging/OnVoyage.Messaging.csproj" />
  </ItemGroup>
</Project>
