<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <ProjectReference Include="../OnVoyage.App.Core/OnVoyage.App.Core.csproj" />
    <ProjectReference Include="../../Shared/OnVoyage.Packs/OnVoyage.Packs.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="OnVoyage.App.LocalData.Tests" />
  </ItemGroup>
</Project>
