namespace OnVoyage.Recommendation.Engine.Learning;

/// <summary>The <c>kind</c> values of §6.2 / §12.4.</summary>
public static class InteractionKinds
{
    public const string OnboardingUp = "onboarding_up";
    public const string OnboardingDown = "onboarding_down";
    public const string OnboardingCategory = "onboarding_category";
    public const string Like = "like";
    public const string Meh = "meh";
    public const string DislikePoi = "dislike_poi";
    public const string DislikeCategory = "dislike_category";
    public const string Listen80 = "listen_80";
    public const string Replay = "replay";
    public const string AbandonEarly = "abandon_early";
    public const string Save = "save";
    public const string Navigate = "navigate";
    public const string Visit = "visit";
    public const string ExternalLink = "external_link";
    public const string CreatorContentOpened = "creator_content_opened";
    public const string Impression = "impression";

    public static IReadOnlySet<string> All { get; } = new HashSet<string>(StringComparer.Ordinal)
    {
        OnboardingUp, OnboardingDown, OnboardingCategory, Like, Meh, DislikePoi, DislikeCategory, Listen80, Replay,
        AbandonEarly, Save, Navigate, Visit, ExternalLink, CreatorContentOpened, Impression,
    };
}

/// <summary>
/// One signal from a traveler. <see cref="ClientEventId"/> is generated by the app so a resend changes nothing. <see cref="Value"/> carries the
/// visit confidence (<c>visit</c>) or the direction of an <c>onboarding_category</c> choice (+1 liked, −1 set aside). No coordinates, ever.
/// </summary>
public sealed record Interaction(
    Guid ClientEventId,
    string Kind,
    string? PoiId,
    DateTimeOffset OccurredAt,
    double Value = 0d,
    string? CategoryCode = null);

/// <summary>Tunable values of §6.2 and §6.4 (⚙️).</summary>
public sealed record LearningOptions
{
    public double Eta { get; init; } = 0.15;
    public double OnboardingEta { get; init; } = 0.35;
    public double CategoryChoice { get; init; } = 0.6;
    public double DislikePoiIntensity { get; init; } = -0.6 * 0.3;
    public double DislikeCategoryIntensity { get; init; } = -1.0;
    public int RepeatedRejections { get; init; } = 3;
    public TimeSpan RepeatedRejectionsWindow { get; init; } = TimeSpan.FromDays(30);
    public TimeSpan LockDuration { get; init; } = TimeSpan.FromDays(30);
}
